routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();
Route::group(['middleware' => ['auth','admin']], function () {
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    Route::get('/notifikasi', 'HomeController@notifikasi')->name('notifikasi');

    Route::prefix('users')->group(function () {
        Route::resource('/divisi', DivisiController::class);
        Route::resource('/posisi', PosisiController::class);
        Route::resource('/posisi-level', PosisiLevelController::class);
        Route::resource('/mutasi', MutasiController::class);

        Route::resource('/karyawan', KaryawanController::class);
        Route::post('/karyawan/change-status/{karyawan}', 'KaryawanController@changeStatus')->name('karyawan.change-status');
    });
 
    Route::prefix('time-management')->group(function () {
        Route::resource('/kehadiran', KehadiranController::class);
        Route::resource('/lembur', LemburController::class);
        Route::resource('/libur', LiburController::class);
        Route::resource('/cuti', CutiController::class);
        Route::post('/cuti/change-status/{cuti}', 'CutiController@changeStatus')->name('cuti.change-status');

        Route::get('/cuti-export', 'CutiController@exportExcel')->name('cuti.export');
        Route::get('/lembur-export', 'LemburController@exportExcel')->name('lembur.export');
        Route::get('/kehadiran-export', 'KehadiranController@exportExcel')->name('kehadiran.export');
        Route::get('/kehadiran/report/create/{id}', 'KehadiranController@createReport')->name('kehadiran.report.create');
        Route::post('/kehadiran/report/store/{id}', 'KehadiranController@storeReport')->name('kehadiran.report.store');
        Route::delete('/kehadiran/report/destroy/{id}', 'KehadiranController@destroyReport')->name('kehadiran.report.destroy');
    });

    Route::prefix('finance')->group(function () {
        Route::resource('/bank', BankController::class);
        Route::resource('/tunjangan', TunjanganController::class);
        Route::resource('/tunjangan-karyawan', TunjanganKaryawanController::class);
        Route::resource('/penggajian', PenggajianController::class);

        Route::resource('/pinjaman', PinjamanController::class);
        Route::post('/pinjaman/change-status/{pinjaman}', 'PinjamanController@changeStatus')->name('pinjaman.change-status');
        Route::get('/pinjaman-export', 'PinjamanController@exportExcel')->name('pinjaman.export');

        Route::resource('/reimbursement', ReimbursementController::class);
        Route::post('/reimbursement/change-status/{reimbursement}', 'ReimbursementController@changeStatus')->name('reimbursement.change-status');
        Route::get('/reimbursement-export', 'ReimbursementController@exportExcel')->name('reimbursement.export');
    });

    Route::prefix('information')->group(function () {
        Route::resource('/informasi', InformasiController::class);
    });
 });

app/Posisi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Posisi extends Model
{
    public function divisi()
    {
        return $this->belongsTo(Divisi::class);
    }

    public function karyawans()
    {
        return $this->hasMany(Karyawan::class);
    }
}

app/Http/Controllers/PosisiController.php
<?php

namespace App\Http\Controllers;

use App\Posisi;
use App\Divisi;
use App\Karyawan;
use Illuminate\Http\Request;

class PosisiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->search;
        $posisis  = Posisi::where('id', '!=', 0);
        if (isset($search) && !empty($search)) {
            $posisis->where('nama_posisi', 'like', '%' . $search . '%');
        }
        $posisis = $posisis->paginate(10);
        return view('posisi.index',[
            'posisis' => $posisis,
            'search' => $search
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $divisis = Divisi::all();
        return view('posisi.create',[
            'divisis' => $divisis,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $posisi = new Posisi();
        $posisi->nama_posisi = $request->nama_posisi;
        $posisi->divisi_id = $request->divisi;
        $posisi->save();

        $this->createNotifikasi([
            'judul' => 'Posisi Baru',
            'keterangan' => 'Posisi '. $request->nama_posisi .' telah ditambahkan pada divisi '.$posisi->divisi->nama_divisi,
            'icon' => 'fa-solid fa-plus',
            'color' => 'success',
        ]);

        session()->flash('success', 'Data Posisi Berhasil Ditambah');
        return redirect()->route('posisi.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Posisi  $posisi
     * @return \Illuminate\Http\Response
     */
    public function show(Posisi $posisi)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Posisi  $posisi
     * @return \Illuminate\Http\Response
     */
    public function edit(Posisi $posisi)
    {
        $divisis = Divisi::all();
        return view('posisi.edit',[
            'divisis' => $divisis,
            'posisi' => $posisi
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Posisi  $posisi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Posisi $posisi)
    {
        $posisi->nama_posisi = $request->nama_posisi;
        $posisi->divisi_id = $request->divisi;
        $posisi->save();


        $this->createNotifikasi([
            'judul' => 'Posisi Diubah',
            'keterangan' => 'Terdapat perubahan data pada Posisi '.$request->nama_posisi,
            'icon' => 'fa-regular fa-pen-to-square',
            'color' => 'secondary',
        ]);

        session()->flash('success', 'Data Posisi Berhasil Diubah');
        return redirect()->route('posisi.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Posisi  $posisi
     * @return \Illuminate\Http\Response
     */
    public function destroy(Posisi $posisi)
    {
        $karyawan = Karyawan::where('posisi_id', $posisi->id)->get();
        if (count($karyawan) == 0) {
            $this->createNotifikasi([
                'judul' => 'Posisi Dihapus',
                'keterangan' => 'Posisi '.$posisi->nama_posisi.' telah dihapus',
                'icon' => 'fa-solid fa-trash-can',
                'color' => 'error',
            ]);
            Posisi::destroy($posisi->id);
            $response = [
                'message' => 'Data Posisi Berhasil Dihapus'
            ];
        } else {
            $response = [
                'error' => true,
                'message' => 'Terdapat Data Karyawan didalam Posisi ini'
            ];
        }
        return response()->json($response);
    }
}

resources/views/posisi/create.blade.php
@extends('layouts.app')

@section('sidebar')
    @include('layouts.sidebar.users')
@endsection

@section('content')
<!-- Main Content Wrapper -->
<main class="main-content w-full px-[var(--margin-x)] pb-8">
    <div class="flex items-center space-x-4 py-5 lg:py-6">
        <h2
        class="text-xl font-medium text-slate-800 dark:text-navy-50 lg:text-2xl"
        >
        Tambah Posisi
        </h2>
        <div class="hidden h-full py-1 sm:flex">
        <div class="h-full w-px bg-slate-300 dark:bg-navy-600"></div>
        </div>
        <ul class="hidden flex-wrap items-center space-x-2 sm:flex">
        <li class="flex items-center space-x-2">
            <a
            class="text-primary transition-colors hover:text-primary-focus dark:text-accent-light dark:hover:text-accent"
            href="{{ route('posisi.index') }}"
            >Pengguna</a
            >
            <svg
            x-ignore
            xmlns="http://www.w3.org/2000/svg"
            class="h-4 w-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            >
            <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M9 5l7 7-7 7"
            />
            </svg>
        </li>
        <li class="flex items-center space-x-2">
            <a
            class="text-primary transition-colors hover:text-primary-focus dark:text-accent-light dark:hover:text-accent"
            href="{{ route('posisi.index') }}"
            >Posisi</a
            >
            <svg
            x-ignore
            xmlns="http://www.w3.org/2000/svg"
            class="h-4 w-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            >
            <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M9 5l7 7-7 7"
            />
            </svg>
        </li>
        <li>Tambah Posisi</li>
        </ul>
    </div>

    <form action="{{ route('posisi.store') }}" method="post">
        @csrf
        <div class="grid grid-cols-12 gap-4 sm:gap-5 lg:gap-6">
            <div class="col-span-12 sm:col-span-12">
                <div class="card p-4 sm:p-5">
                    <p
                    class="text-base font-medium text-slate-700 dark:text-navy-100"
                    >
                    Data Posisi
                    </p>
                    <div class="mt-4 space-y-4">
                    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                        <label class="block">
                            <span>Nama Posisi</span>
                            <span class="relative mt-1.5 flex">
                                <input
                                class="form-input peer w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 pl-9 placeholder:text-slate-400/70 hover:border-slate-400 focus:border-primary dark:border-navy-450 dark:hover:border-navy-400 dark:focus:border-accent"
                                placeholder="Nama Posisi"
                                type="text"
                                name="nama_posisi"
                                required
                                />
                                <span
                                class="pointer-events-none absolute flex h-full w-10 items-center justify-center text-slate-400 peer-focus:text-primary dark:text-navy-300 dark:peer-focus:text-accent"
                                >
                                <i class="fa-solid fa-people-line"></i>
                                </span>
                            </span>
                        </label>
                        <label class="block">
                            <span>Divisi</span>
                            <select
                                class="mt-1.5 w-full"
                                x-init="$el._x_tom = new Tom($el,{create: false})"
                                required
                                name="divisi"
                            >
                                <option selected disabled>Pilih Divisi</option>
                                @foreach($divisis as $divisi)
                                    <option value="{{$divisi->id}}">{{$divisi->nama_divisi}}</option>
                                @endforeach
                            </select>
                        </label>
                    </div>
                    </div>
                </div>
            </div>
    
    
            <div class="col-span-12 sm:col-span-12 mt-5">
                <div class="card p-4 sm:p-5">
    
                    <div class="flex justify-end space-x-2">
                        <a 
                        type="button"
                        href="{{route('posisi.index')}}"
                        class="btn space-x-2 bg-slate-150 font-medium text-slate-800 hover:bg-slate-200 focus:bg-slate-200 active:bg-slate-200/80 dark:bg-navy-500 dark:text-navy-50 dark:hover:bg-navy-450 dark:focus:bg-navy-450 dark:active:bg-navy-450/90"
                        >
                        <span>Kembali</span>
                        </a>
                        <button
                        class="btn space-x-2 bg-primary font-medium text-white hover:bg-primary-focus focus:bg-primary-focus active:bg-primary-focus/90 dark:bg-accent dark:hover:bg-accent-focus dark:focus:bg-accent-focus dark:active:bg-accent/90"
                        >
                        <span>Simpan</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    </div>
    </main>
@endsection

resources/views/posisi/edit.blade.php
@extends('layouts.app')

@section('sidebar')
    @include('layouts.sidebar.users')
@endsection

@section('content')
<!-- Main Content Wrapper -->
<main class="main-content w-full px-[var(--margin-x)] pb-8">
    <div class="flex items-center space-x-4 py-5 lg:py-6">
        <h2
        class="text-xl font-medium text-slate-800 dark:text-navy-50 lg:text-2xl"
        >
        Ubah Posisi
        </h2>
        <div class="hidden h-full py-1 sm:flex">
        <div class="h-full w-px bg-slate-300 dark:bg-navy-600"></div>
        </div>
        <ul class="hidden flex-wrap items-center space-x-2 sm:flex">
        <li class="flex items-center space-x-2">
            <a
            class="text-primary transition-colors hover:text-primary-focus dark:text-accent-light dark:hover:text-accent"
            href="{{ route('posisi.index') }}"
            >Pengguna</a
            >
            <svg
            x-ignore
            xmlns="http://www.w3.org/2000/svg"
            class="h-4 w-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            >
            <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M9 5l7 7-7 7"
            />
            </svg>
        </li>
        <li class="flex items-center space-x-2">
            <a
            class="text-primary transition-colors hover:text-primary-focus dark:text-accent-light dark:hover:text-accent"
            href="{{ route('posisi.index') }}"
            >Posisi</a
            >
            <svg
            x-ignore
            xmlns="http://www.w3.org/2000/svg"
            class="h-4 w-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            >
            <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M9 5l7 7-7 7"
            />
            </svg>
        </li>
        <li>Ubah Posisi</li>
        </ul>
    </div>

    <form action="{{ route('posisi.update', $posisi->id) }}" method="post">
        @method('PUT')
        @csrf
        <div class="grid grid-cols-12 gap-4 sm:gap-5 lg:gap-6">
            <div class="col-span-12 sm:col-span-12">
                <div class="card p-4 sm:p-5">
                    <p
                    class="text-base font-medium text-slate-700 dark:text-navy-100"
                    >
                    Data Posisi
                    </p>
                    <div class="mt-4 space-y-4">
                    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                        <label class="block">
                            <span>Nama Posisi</span>
                            <span class="relative mt-1.5 flex">
                                <input
                                class="form-input peer w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 pl-9 placeholder:text-slate-400/70 hover:border-slate-400 focus:border-primary dark:border-navy-450 dark:hover:border-navy-400 dark:focus:border-accent"
                                placeholder="Nama Posisi"
                                type="text"
                                name="nama_posisi"
                                value="{{ $posisi->nama_posisi }}"
                                required
                                />
                                <span
                                class="pointer-events-none absolute flex h-full w-10 items-center justify-center text-slate-400 peer-focus:text-primary dark:text-navy-300 dark:peer-focus:text-accent"
                                >
                                <i class="fa-solid fa-people-line"></i>
                                </span>
                            </span>
                        </label>
                        <label class="block">
                            <span>Divisi</span>
                            <select
                                class="mt-1.5 w-full"
                                x-init="$el._x_tom = new Tom($el,{create: false})"
                                required
                                name="divisi"
                            >
                                <option selected disabled>Pilih Divisi</option>
                                @foreach($divisis as $divisi)
                                    <option value="{{$divisi->id}}" {{$posisi->divisi_id == $divisi->id ? 'selected' : ''}}>{{$divisi->nama_divisi}}</option>
                                @endforeach
                            </select>
                        </label>
                    </div>
                    </div>
                </div>
            </div>
    
    
            <div class="col-span-12 sm:col-span-12 mt-5">
                <div class="card p-4 sm:p-5">
    
                    <div class="flex justify-end space-x-2">
                        <a 
                        type="button"
                        href="{{route('posisi.index')}}"
                        class="btn space-x-2 bg-slate-150 font-medium text-slate-800 hover:bg-slate-200 focus:bg-slate-200 active:bg-slate-200/80 dark:bg-navy-500 dark:text-navy-50 dark:hover:bg-navy-450 dark:focus:bg-navy-450 dark:active:bg-navy-450/90"
                        >
                        <span>Kembali</span>
                        </a>
                        <button
                        class="btn space-x-2 bg-primary font-medium text-white hover:bg-primary-focus focus:bg-primary-focus active:bg-primary-focus/90 dark:bg-accent dark:hover:bg-accent-focus dark:focus:bg-accent-focus dark:active:bg-accent/90"
                        >
                        <span>Ubah</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    </div>
    </main>
@endsection